# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#front matter
# ---
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "default"
# ---
# Site settings
title: Aishwarya Venkataramanan
email: vaishwarya96@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
        #This is my personal record of interesting programming tips, computer science
        #theories, and any of the feelings I'd like to share with the community.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: vaishwarya96

# Build settings
markdown: kramdown




