# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#front matter
# ---
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "default"
# ---
# Site settings
title: Aishwarya Venkataramanan
email: vaishwarya96@gmail.com
description: > this means to ignore newlines until "baseurl:"
This is the base Jekyll theme. You can find out more info about customizing your Jekyll theme, as well as basic Jekyll usage documentation at [jekyllrb.com](http://jekyllrb.com/)

You can find the source code for the Jekyll new theme at:
{% include icon-github.html username="jglovier" %} /
[jekyll-new](https://github.com/jglovier/jekyll-new)

You can find the source code for Jekyll at
{% include icon-github.html username="jekyll" %} /
[jekyll](https://github.com/jekyll/jekyll)

baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: vaishwarya96
linkedin_username: aishwarya-venkataramanan

# Build settings
markdown: kramdown




